services:
  oak_mysql:
    image: mysql:9.3.0
    container_name: oak_mysql
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: oak
    ports:
      - 127.0.0.1:$OAK_MYSQL_PORT:3306

  oak_redis:
    image: redis:6.2.4
    container_name: oak_redis

  oak_prod_test_mysql:
    image: mysql:9.3.0
    container_name: oak_prod_test_mysql
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: oak
    ports:
      - 127.0.0.1:$OAK_MYSQL_PORT:3306

  oak_prod_redis:
    image: redis:6.2.4
    container_name: oak_prod_redis

  oak_photos:
    image: httpd:latest
    volumes:
      - ./dev_public_files:/usr/local/apache2/htdocs
    ports:
      - 127.0.0.1:3001:80
  #################### Base  ####################

  base: &base
    image: darthjee/oak
    volumes:
      - ./source:/home/app/app
    links:
      - oak_mysql:mysql
      - oak_redis:redis
    env_file: .env

  prod_base: &prod_base
    env_file: .env.production
    image: darthjee/production_oak
    environment:
      RAILS_ENV: production
      REDIS_URL: redis://redis:6379/1
    links:
      - oak_prod_redis:redis

  base_build:
    <<: *base
    build:
      context: .
      dockerfile: Dockerfile.oak
    command: echo done

  base_prod_build:
    <<: *prod_base
    build:
      context: .
      dockerfile: Dockerfile.production_oak
    command: echo done

  #################### CONTAINERS ####################

  oak_app:
    <<: *base
    container_name: oak_app
    command: /bin/bash bin/test_server.sh
    depends_on: [base_build, oak_photos, oak_sidekiq]
    ports:
      - 127.0.0.1:3000:3000
    environment:
      - RAILS_ENV=development
      - OAK_MYSQL_PORT=3306

  oak_sidekiq:
    <<: *base
    container_name: oak_sidekiq
    command: /bin/bash bin/sidekiq.sh
    volumes:
      - ./dev_public_files:/tmp/photos
    environment:
      - RAILS_ENV=development
      - OAK_MYSQL_PORT=3306

  oak_tests:
    <<: *base
    container_name: oak_tests
    command: /bin/bash bin/tests.sh
    depends_on: [base_build]
    environment:
      - RAILS_ENV=test

  oak_root:
    <<: *base
    user: root
    container_name: oak_root
    command: /bin/bash
    depends_on: [base_build]

  oak_production:
    <<: *prod_base
    container_name: oak_production
    depends_on: [base_prod_build, oak_prod_sidekiq]
    command: bin/server.sh
    ports:
      - 127.0.0.1:3002:3000

  oak_prod_test:
    <<: *prod_base
    container_name: oak_production_test
    depends_on: [base_prod_build]
    command: bin/test_server.sh
    ports:
      - 127.0.0.1:3002:3000
    links:
      - oak_prod_test_mysql:mysql

  oak_prod_sidekiq:
    <<: *prod_base
    container_name: oak_prod_sidekiq
    depends_on: [base_prod_build]
    command: /bin/bash bin/sidekiq.sh
    volumes:
      - ./prod_public_files/photos:/tmp/photos
