version: 2
workflows:
  version: 2
  test:
    jobs:
      - test:
          filters:
            tags:
              only: /.*/
      - checks:
          filters:
            tags:
              only: /.*/
      - build-and-release:
          requires: [test, checks]
          filters:
            tags:
              only: /.*/
            branches:
              only:
                - master
jobs:
  test:
    docker:
      - image: darthjee/circleci_oak-base:0.0.3
        environment:
          OAK_MYSQL_HOST: mysql
          OAK_MYSQL_PORT: 3306
          OAK_MYSQL_USER: oak
          OAK_MYSQL_NAME: oak
          OAK_MYSQL_PASSWORD: oak
          OAK_PASSWORD_SALT: abcd
      - image: circleci/mysql:5.7
        name: mysql
        environment:
          MYSQL_DATABASE: oak_test
          MYSQL_USER: oak
          MYSQL_PASSWORD: oak
    steps:
      - checkout
      - run:
          name: Set folder
          command: cp source/* source/.??* ./ -r; rm source -rf
      - run:
          name: Prepare Coverage Test Report
          command: cc-test-reporter before-build
      - run:
          name: Bundle Install
          command: bundle install
      - run:
          name: Yarn Install
          command: yarn install
      - run:
          name: Wait for database
          command: scripts/wait_for_db.sh
      - run:
          name: Migrate
          command: RAILS_ENV=test bundle exec rake db:schema:load
      - run:
          name: RSpec
          command: bundle exec rspec

  checks:
    docker:
      - image: darthjee/circleci_oak-base:0.0.3
        environment:
          OAK_MYSQL_HOST: mysql
          OAK_MYSQL_PORT: 3306
          OAK_MYSQL_USER: oak
          OAK_MYSQL_NAME: oak
          OAK_MYSQL_PASSWORD: oak
          OAK_PASSWORD_SALT: abcd
      - image: circleci/mysql:5.7
        name: mysql
        environment:
          MYSQL_DATABASE: oak_test
          MYSQL_USER: oak
          MYSQL_PASSWORD: oak
    steps:
      - checkout
      - run:
          name: Set folder
          command: cp source/* source/.??* ./ -r; rm source -rf
      - run:
          name: Bundle Install
          command: bundle install
      - run:
          name: Rubocop
          command: rubocop
  build-and-release:
    machine: true
    steps:
      - checkout
      - run:
          name: Trigger Deploy
          command: scripts/deploy.sh deploy
