web:
  port: $NAVI_PORT
workers:
  quantity: 5
  retry_cooldown: 10000
  sleep: 500
  max-retries: 50

failure:
  threshold: 0.0

clients:
  default:
    base_url: $OAK_PRODUCTION_URL
    timeout: 20000

resources:
  home:
    - url: /
      status: 200
      assets:
        - selector: 'link[rel="stylesheet"]'
          attribute: href
        - selector: 'script[src]'
          attribute: src

  user_navigation:
    - url: /user/categories.json
      status: 200

  categories:
    - url: /categories.json
      status: 200
      paginated_actions:
        - resource: paginated_categories
          pagination:
            - pages: headers['pages']
            - page_key: page
            - zero_indexed: false
    - url: /categories
      status: 302

  paginated_categories:
    - url: /categories.json?page={:page}
      status: 200
      actions:
        - resource: category
          parameters:
            slug: parsedBody.slug
        - resource: category_items
          parameters:
            category_slug: parsedBody.slug
    - url: /categories?page={:page}
      status: 302

  category:
    - url: /categories/{:slug}.json
      status: 200
    - url: /categories/{:slug}
      status: 302

  category_items:
    - url: /categories/{:category_slug}/items.json
      status: 200
      paginated_actions:
        - resource: paginated_category_items
          pagination:
            - pages: headers['pages']
            - page_key: page
            - zero_indexed: false
    - url: /categories/{:category_slug}/items
      status: 302

  paginated_category_items:
    - url: /categories/{:category_slug}/items.json?page={:page}
      status: 200
      actions:
        - resource: category_item
          parameters:
            id: parsedBody.id
            category_slug: parsedBody.category_slug
    - url: /categories/{:category_slug}/items?page={:page}
      status: 302

  category_item:
    - url: /categories/{:category_slug}/items/{:id}.json
      status: 200
    - url: /categories/{:category_slug}/items/{:id}
      status: 302

  kinds:
    - url: /kinds.json
      status: 200
      paginated_actions:
        - resource: paginated_kinds
          pagination:
            - pages: headers['pages']
            - page_key: page
            - zero_indexed: false
    - url: /kinds
      status: 302

  paginated_kinds:
    - url: /kinds.json?page={:page}
      status: 200
      actions:
        - resource: kind
          parameters:
            slug: parsedBody.slug
    - url: /kinds?page={:page}
      status: 302

  kind:
    - url: /kinds/{:slug}.json
      status: 200
    - url: /kinds/{:slug}
      status: 302
