# frozen_string_literal: true

source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '3.3.1'

gem 'importmap-rails'
gem 'jbuilder'
gem 'mysql2'
gem 'puma', '>= 7.2.0'
gem 'rails', '~> 7.2.x'
gem 'sidekiq', '~> 7.0'
gem 'sprockets-rails'
gem 'stimulus-rails'
gem 'turbo-rails'
gem 'rake', '>= 13.2.1'
gem 'turbolinks', '>= 5.2.1'

gem 'bootsnap', require: false
gem 'globalid', '>= 1.1.0'
gem 'rack', '>= 2.2.6.3'
gem 'sassc-rails', '>= 2.1.2'
gem 'tzinfo-data'
gem 'uglifier', '>= 4.2.1'
gem 'sass-rails', '>= 6.0.0'
gem 'docile', '>= 1.4.1'
gem 'nokogiri', '>= 1.19.1'

gem 'azeroth',             '>=2.2.0'
gem 'darthjee-active_ext', '>= 1.4.0'
gem 'darthjee-core_ext',   '>= 3.1.0'
gem 'magicka',             '>= 1.2.0'
gem 'sinclair',            '>= 3.1.0'
gem 'tarquinn',            '>= 0.5.0'
gem 'zyra',                '>= 1.3.0'
gem 'jace',                '>= 0.1.2'

group :development, :test do
  gem 'factory_bot',               '>= 6.2.1'
  gem 'pry',                       '>= 0.14.2'
  gem 'pry-nav',                   '>= 1.0.0'
  gem 'pry-rails',                 '>= 0.3.11'
  gem 'reek',                      '>= 6.5.0'
  gem 'rspec',                     '>= 3.13.2'
  gem 'rspec-core',                '>= 3.13.6'
  gem 'rspec-expectations',        '>= 3.13.5'
  gem 'rspec-mocks',               '>= 3.13.8'
  gem 'rspec-rails',               '>= 8.0.0'
  gem 'rspec-support',             '>= 3.13.7'
  gem 'rubocop',                   '1.85.1'
  gem 'rubocop-factory_bot',       '2.28.0'
  gem 'rubocop-rails',             '2.34.3'
  gem 'rubocop-rake',              '0.7.1'
  gem 'rubocop-rspec',             '3.9.0'
  gem 'rubocop-rspec_rails',       '2.32.0'
  gem 'rubycritic',                '>= 5.0.0'
  gem 'shoulda-matchers',          '>= 7.0.1'
  gem 'simplecov',                 '>= 0.22.0'
  gem 'simplecov-html',            '0.13.2'
  gem 'simplecov-lcov',            '0.9.0'
  gem 'timecop',                   '>= 0.9.10'
  gem 'yard',                      '0.9.38'
  gem 'yardstick',                 '0.9.9'
  gem 'zonebie',                   '0.6.1'

  gem 'rails-controller-testing',  '1.0.5'
end

group :development do
  gem 'web-console', '4.2.1'
end

group :test do
  gem 'database_cleaner', '2.0.2'
  gem 'webmock',          '3.26.1'

  gem 'rspec-collection_matchers', '1.2.1'
end
